######################################################################################
#     ____   ____.__                    .__  ___________.__                          #
#     \   \ /   /|__| ________ _______  |  | \_   _____/|__|__  ___ ___________      #
#      \   Y   / |  |/  ___/  |  \__  \ |  |  |    __)  |  \  \/  // __ \_  __ \     #
#       \     /  |  |\___ \|  |  // __ \|  |__|    \    |  |>    <\  ___/|  | \/     #
#        \___/   |__/____  >____/(____  /____/\____/    |__/__/\_ \\___  >__|        #
#                        \/           \/                         \/    \/            #
#                                                                                    #
######################################################################################

# Will be flower pots fixed?
fix-pots: true

# Will be double plant fixed?
fix-double-plants: true

# Will be fast breaking blocks fixed?
fix-fast-break: true

# Will be place flowers inside pot fixed?
fix-pot-place: true

# Will be break pistons extension fixed?
fix-pistons: true

# Will be advanced checks used?
# (Use them only in case of strange bugs)
advanced-check: false

# Do not touch this number!
config-version: 3