main: com.fren_gor.visualFixer.Main
version: 1.2
name: VisualFixer
author: fren_gor

commands:
  fixvisual:
    description: Fix the blocks around the player
    permission: visualfix.command
  visualfixer:
    description: Fix the blocks around the player

permissions:
  visualfix.fixvisual:
    description: Use the command /fixvisual of the plugin VisualFixer
    default: true
  visualfix.visualfixer:
    description: Use the command /visualfixer of the plugin VisualFixer
    default: true