main: com.fren_gor.visualFixer.Main
version: ${project.version}
name: ${project.name}
author: fren_gor
website: ${project.url}
description: ${project.description}

api-version: 1.13

commands:
  fixvisual:
    description: Fix the blocks around the player
    permission: visualfix.command
  visualfixer:
    description: Fix the blocks around the player

permissions:
  visualfix.*:
    description: All the permissions
    default: op
    children:
      visualfix.fixvisual: true
      visualfix.visualfixer: true
  visualfix.fixvisual:
    description: Use the command /fixvisual of the plugin VisualFixer
    default: true
  visualfix.visualfixer:
    description: Use the command /visualfixer of the plugin VisualFixer
    default: op
